"""empty message

Revision ID: 66b18b229bbf
Revises: d5a88426c7b5
Create Date: 2021-05-10 14:26:40.996233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b18b229bbf'
down_revision = 'd5a88426c7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('battery_logger_ibfk_1', 'battery_logger', type_='foreignkey')
    op.create_foreign_key(None, 'battery_logger', 'device', ['device_id'], ['id'], onupdate='cascade', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'battery_logger', type_='foreignkey')
    op.create_foreign_key('battery_logger_ibfk_1', 'battery_logger', 'device', ['device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
