"""empty message

Revision ID: d5a88426c7b5
Revises: 
Create Date: 2021-03-19 18:23:58.840503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5a88426c7b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battery_many_relation_table')
    op.add_column('battery_logger', sa.Column('device_id', sa.Integer(), nullable=False))
    op.alter_column('battery_logger', 'device_battery',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.create_foreign_key(None, 'battery_logger', 'device', ['device_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.drop_column('user', 'username')
    op.drop_column('user', 'tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tokens', mysql.TEXT(), nullable=True))
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=64), nullable=True))
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.drop_constraint(None, 'battery_logger', type_='foreignkey')
    op.alter_column('battery_logger', 'device_battery',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.drop_column('battery_logger', 'device_id')
    op.create_table('battery_many_relation_table',
    sa.Column('device_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('battery_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['battery_id'], ['battery_logger.id'], name='battery_many_relation_table_ibfk_1'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='battery_many_relation_table_ibfk_2'),
    sa.PrimaryKeyConstraint('device_id', 'battery_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
